export type EntityType =
  | 'user'
  | 'workspace'
  | 'board'
  | 'cardList'
  | 'card'
  | 'memberRole'
  | 'memberCreator'
  | 'addedMember'
  | 'joinedMember'
  | 'requester'
  | 'updatedMember'
  | 'removedMember'
  | 'removedGuest'
